name = "reserve-saas"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://sagmcmfputhcfisvglbx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_eV_eT3ojdX5jGIHfh3qJQA_jcoi-tKs"
